import createFetchClient, {
  createFinalURL,
  createQuerySerializer,
  defaultPathSerializer,
  type FetchResponse,
  type ParamsOption,
  type RequestBodyOption,
} from "openapi-fetch";
import type { HttpMethod, PathsWithMethod } from "openapi-typescript-helpers";
import React from "react";
import type { ConditionalExcept, Simplify } from "type-fest";

/**
 * Creates a type-safe React data-fetching client bound to an OpenAPI schema.
 *
 * All hooks and imperative helpers returned by a single `createClient` call
 * share one in-memory cache. Clients created with separate `createClient` calls
 * have independent caches and do not share state.
 *
 * @typeParam Paths - The OpenAPI `Paths` object generated by `openapi-typescript`.
 *   Pass your generated types here to get end-to-end type safety on every path,
 *   method, param, and response.
 *
 * @example
 * ```ts
 * // api.ts — create once, import everywhere
 * import createClient from "@beyond.dev/openapi-react";
 * import type { paths } from "./openapi-schema"; // generated by openapi-typescript
 *
 * export const api = createClient<paths>({
 *   baseUrl: "https://api.example.com",
 *   requestInit: () => ({
 *     headers: { Authorization: `Bearer ${getToken()}` },
 *   }),
 * });
 * ```
 *
 * @example
 * ```ts
 * // Multi-tenant: extend cache key with org ID so tenant A never sees tenant B's data
 * export const api = createClient<paths>({
 *   baseUrl: "https://api.example.com",
 *   extendCacheKey: (opt) => ({ ...opt, orgId: getOrgId() }),
 * });
 * ```
 */
export function createClient<Paths extends {}>(
  options: ClientOptions<Paths> = {},
) {
  const {
    baseUrl = "",
    cacheTime = 5 * 60 * 1000,
    staleTime: defaultStaleTime = 1000,
    retries: defaultRetries = 3,
    shouldRetry: defaultShouldRetry = defaultShouldRetryOnError,
    requestInit: defaultRequestInit,
    querySerializer = createQuerySerializer(),
    debug,
    onEachSuccess,
    onEachError,
  } = options;
  const cache = new SubjectMap<
    string,
    CachedResponse<Paths, LoadablePaths<Paths>>
  >();
  const refCount = new Map<string, number>();
  const client = createFetchClient<Paths>({
    baseUrl,
    ...defaultRequestInit?.(),
  });

  function createKey(opt: {
    path: `GET ${LoadablePaths<Paths>}`;
    input?: Record<string, unknown>;
  }) {
    return encodeKey(
      options.extendCacheKey ? options.extendCacheKey(opt) : opt,
    );
  }

  const evictionInterval = setInterval(
    () => {
      const now = Date.now();
      for (const key of cache.keys()) {
        if (refCount.get(key)) continue;
        const cached = cache.get(key);
        if (cached && cached.createdAt + cacheTime < now) {
          cache.delete(key);
        }
      }
    },
    Math.min(cacheTime / 4, 5000),
  );

  /**
   * Builds a fully-qualified URL for a path+method without making a request.
   *
   * Useful for constructing `<img src>`, `<a href>`, or any URL you need to
   * hand to a third-party library that manages its own fetch.
   *
   * @example
   * ```tsx
   * // GET /users/{id}/avatar → "https://api.example.com/users/42/avatar?size=128"
   * const src = api.url({
   *   path: "GET /users/{id}/avatar",
   *   input: { path: { id: 42 }, query: { size: 128 } },
   * });
   * return <img src={src} />;
   * ```
   */
  function url<
    M extends Uppercase<HttpMethod>,
    P extends Extract<PathsWithMethod<Paths, Lowercase<M>>, string>,
  >(options: {
    path: `${M} ${P}`;
    input: Paths[P] extends Record<Lowercase<M>, any> ? Partial<
        Pick<ParamsOption<Paths[P][Lowercase<M>]>["params"], "query" | "path">
      >
      : never;
  }): string {
    const { path, input, ...o } = options;
    return createFinalURL(path.split(" ").at(1)!, {
      ...o,
      params: input,
      baseUrl,
      querySerializer,
      pathSerializer: defaultPathSerializer,
    });
  }

  /**
   * Issues a one-off typed HTTP request without touching the cache.
   *
   * Use this when you need a raw response — forms, server actions, fire-and-forget
   * side effects — and don't want cache semantics. For cached GETs, use `load` or
   * `useLoader` instead.
   *
   * The method and path are encoded together as a single string literal
   * (`"POST /users"`, `"DELETE /items/{id}"`) so TypeScript can narrow the
   * correct request and response types automatically.
   *
   * @returns The raw `openapi-fetch` response object `{ data, error, response }`.
   *
   * @example
   * ```ts
   * const { data, error } = await api.fetch("POST /users", {
   *   input: { body: { name: "Alice", email: "alice@example.com" } },
   * });
   *
   * if (error) throw new Error(error.message);
   * console.log(data.id); // typed: number
   * ```
   *
   * @example
   * ```ts
   * // DELETE with a path parameter
   * await api.fetch("DELETE /users/{id}", {
   *   input: { path: { id: 42 } },
   * });
   * ```
   */
  async function fetch_<
    Method extends Uppercase<HttpMethod>,
    Path extends Extract<PathsWithMethod<Paths, Lowercase<Method>>, string>,
  >(
    methodPath: `${Method} ${Path}`,
    requestInit?:
      & Omit<RequestInit, "method" | "body">
      & Input<Paths, Path, Lowercase<Method>>,
  ): Promise<Output<Paths, Path, Lowercase<Method>>> {
    const spaceIdx = methodPath.indexOf(" ");
    const method = methodPath.slice(0, spaceIdx) as Method;
    const path = methodPath.slice(spaceIdx + 1);
    const { input: i, ...init } = (requestInit ?? {}) as typeof requestInit & {
      input?: { body?: unknown } & Record<string, unknown>;
    };
    const { body, ...input } = i ?? {};
    // @ts-expect-error: dynamic HTTP method dispatch on openapi-fetch client
    const res = await client[method](path, {
      ...defaultRequestInit?.(),
      ...init,
      params: input,
      body,
    });

    if (debug) {
      logResponse(res);
    }

    return res;
  }

  /**
   * Fetches a GET endpoint and writes the result into the shared cache.
   *
   * - If a non-stale entry exists (within `staleTime`), returns it immediately
   *   without issuing a network request.
   * - If a fetch for the same key is already in-flight, awaits that request
   *   instead of issuing a duplicate.
   * - On HTTP 5xx, retries with exponential backoff up to `retries` times.
   * - On abort (unmount), resolves with stale data if available; otherwise rethrows.
   *
   * Use `load` outside React (route loaders, server actions, test setup) or when you
   * want to prime the cache before a component mounts. Inside components, prefer
   * `useLoader` or `useInlineLoader`.
   *
   * @returns A `CachedResponse` with `status: "success"` or `status: "error"`.
   *   Never rejects for HTTP errors — the error is encoded in the returned object.
   *   Does reject for non-HTTP errors (network failures after all retries exhausted,
   *   aborted requests without stale data).
   *
   * @example
   * ```ts
   * // Route loader: prime the cache before the component tree renders
   * export async function loader() {
   *   const { data, error } = await api.load({ path: "GET /users" });
   *   if (error) throw new Response("Failed to load users", { status: 500 });
   *   return data;
   * }
   * ```
   *
   * @example
   * ```ts
   * // Fetch with query params + abort signal
   * const controller = new AbortController();
   * const cached = await api.load({
   *   path: "GET /search",
   *   input: { query: { q: "react", page: 1 } },
   *   signal: controller.signal,
   *   staleTime: 30_000, // serve cached results for 30s
   * });
   * ```
   */
  async function load<Path extends LoadablePaths<Paths>>(
    options: LoadOptions<Paths, Path>,
  ): Promise<CachedResponse<Paths, Path>> {
    const {
      path,
      staleTime = defaultStaleTime,
      retries = defaultRetries,
      shouldRetry = defaultShouldRetry,
      signal = null,
    } = options;
    const optInput = (options as { input?: Record<string, unknown> }).input;
    const cacheKey = createKey(
      optInput !== undefined ? { path, input: optInput } : { path },
    );
    const cached = cache.get(cacheKey);

    if (
      cached
      && (Date.now() < cached.createdAt + staleTime
        || cached.status === "refetching"
        || cached.status === "fetching")
    ) {
      if (debug) {
        console.log(
          `%c📦 ${path} (cached; ttl=${
            cached.createdAt + staleTime - Date.now()
          }ms)`,
          "color: #999",
        );
      }

      await cached.promise;
      return cached;
    }

    if (cached) {
      cached.status = "refetching";
      cached.createdAt = Date.now();
    }

    const nextCached: CachedResponse<Paths, Path> = cached
      ? { ...cached }
      : {
        data: undefined,
        error: undefined,
        response: undefined,
        status: "fetching",
        promise: Promise.resolve(),
        createdAt: Date.now(),
      };

    cache.set(cacheKey, nextCached);
    nextCached.promise = retry<
      Data<Paths, Path, "get">,
      ErrorResponse<ErrorData<Paths, Path, "get">>
    >(
      async () => {
        // Strips "GET " prefix; cast narrows string to the specific path union type
        const getPath = path.replace(/^GET /, "") as PathsWithMethod<
          Paths,
          "get"
        >;
        // init params can't be statically verified against the generic path union
        const res = await client.GET(getPath, {
          ...defaultRequestInit?.(),
          signal,
          params: (options as { input?: Record<string, unknown> }).input,
        } as any);

        if (debug) {
          logResponse(res);
        }

        if (res.error) {
          throw new ErrorResponse<ErrorData<Paths, Path, "get">>(
            res.error as ErrorData<Paths, Path, "get">,
            res.response,
          );
        }

        return {
          data: res.data as Data<Paths, Path, "get">,
          response: res.response!,
        };
      },
      retries,
      async (error, retryCount) => {
        const doRetry = await Promise.resolve(
          shouldRetry?.(error, retryCount),
        ).catch(() => false);
        if (doRetry === false) return false;
        await new Promise<void>((resolve) => {
          setTimeout(resolve, 2 ** retryCount * (Math.random() * 500));
        });
        return doRetry;
      },
    ).then(
      (res) => {
        nextCached.data = res.data as Data<Paths, Path, "get">;
        nextCached.status = "success";
        nextCached.error = undefined;
        nextCached.response = res.response;
        nextCached.createdAt = Date.now();
        cache.set(cacheKey, { ...nextCached });
        return nextCached;
      },
      (error: unknown) => {
        if (error instanceof Error && error.name === "AbortError") {
          const existing = cache.get(cacheKey);
          if (existing && existing.data !== undefined) {
            return existing;
          }
          throw error;
        }

        if (!(error instanceof ErrorResponse)) {
          cache.delete(cacheKey);
          throw error;
        }

        nextCached.status = "error";
        nextCached.error = error.data;
        nextCached.response = error.response;
        nextCached.createdAt = Date.now();
        cache.set(cacheKey, { ...nextCached });
        return nextCached;
      },
    );

    await nextCached.promise;
    return nextCached;
  }

  /**
   * Pre-populates the cache with data you already have — no network request.
   *
   * A no-op when a successful entry for the key already exists. This makes it
   * safe to call unconditionally on every render: it only writes on the first call
   * (or after a purge).
   *
   * The primary use-case is hydrating the client-side cache from data fetched on
   * the server (SSR, RSC, `getServerSideProps`). The client mounts, finds the data
   * immediately, and skips the initial fetch.
   *
   * @example
   * ```tsx
   * // Next.js pages router — hydrate cache from server-fetched data
   * export async function getServerSideProps() {
   *   const users = await fetchUsers(); // your server-side call
   *   return { props: { users } };
   * }
   *
   * export default function Page({ users }: Props) {
   *   api.hydrate({ path: "GET /users", data: users }); // writes only if cache is empty
   *
   *   const { data } = api.useLoader({ path: "GET /users" });
   *   return <UserList users={data} />;
   * }
   * ```
   */
  function hydrate<Path extends LoadablePaths<Paths>>(
    options: {
      path: `GET ${Path}`;
      data: Data<Paths, Path, "get">;
    } & Input<Paths, Path, "get">,
  ): void {
    const optInput = (options as { input?: Record<string, unknown> }).input;
    const cacheKey = createKey(
      optInput !== undefined
        ? { path: options.path, input: optInput }
        : { path: options.path },
    );
    if (cache.get(cacheKey)?.status === "success") return;
    const entry: CachedResponse<Paths, Path> = {
      data: options.data,
      error: undefined,
      response: undefined,
      status: "success",
      createdAt: Date.now(),
      promise: Promise.resolve(options.data),
    };
    cache.set(cacheKey, entry);
  }

  /**
   * Fetches a GET endpoint and subscribes to its cache entry.
   *
   * This is the Suspense-first hook. When data is loading, it throws a Promise
   * so a parent `<Suspense>` boundary can render a fallback. When an error
   * occurs (and `suspense: true`), it throws an `ErrorResponse` so an
   * `<ErrorBoundary>` can render a fallback.
   *
   * All trigger options (`refetchOnMount`, `refetchOnFocus`, `refetchOnReconnect`,
   * `refetchInterval`) are enabled by default and automatically start/stop
   * background polling without any extra setup.
   *
   * Set `disabled: true` to completely skip fetching. The hook returns
   * `{ status: "disabled", data: undefined }` and issues no requests. TypeScript
   * narrows the return type accordingly when `disabled` is a literal `true`.
   *
   * @example
   * ```tsx
   * // Basic usage with Suspense + ErrorBoundary
   * function UserList() {
   *   const { data, invalidate } = api.useLoader({ path: "GET /users" });
   *   //     ^^ typed: User[] — data is always defined here (Suspense guarantees it)
   *
   *   return (
   *     <ul>
   *       {data.map((u) => <li key={u.id}>{u.name}</li>)}
   *     </ul>
   *   );
   * }
   *
   * function App() {
   *   return (
   *     <ErrorBoundary fallback={<p>Failed to load users.</p>}>
   *       <Suspense fallback={<Spinner />}>
   *         <UserList />
   *       </Suspense>
   *     </ErrorBoundary>
   *   );
   * }
   * ```
   *
   * @example
   * ```tsx
   * // With path params + polling every 5 seconds
   * const { data } = api.useLoader({
   *   path: "GET /rooms/{id}/messages",
   *   input: { path: { id: roomId } },
   *   refetchInterval: 5_000,
   * });
   * ```
   *
   * @example
   * ```tsx
   * // Adaptive polling — slow down when data is stale/undefined
   * const { data } = api.useLoader({
   *   path: "GET /jobs/{id}",
   *   input: { path: { id: jobId } },
   *   refetchInterval: (data) => data?.status === "running" ? 2_000 : false,
   * });
   * ```
   *
   * @example
   * ```tsx
   * // Conditional fetch — skip until we have a user ID
   * const { data } = api.useLoader({
   *   path: "GET /users/{id}/profile",
   *   input: { path: { id: userId! } },
   *   disabled: !userId,
   * });
   * ```
   */
  function useLoader<
    Path extends LoadablePaths<Paths>,
    Disabled extends Readonly<boolean> = false,
  >(
    options: UseLoaderOptions<Paths, Path, Disabled>,
  ): UseLoaderResult<Paths, Path, Disabled> {
    const {
      staleTime = defaultStaleTime,
      disabled = false as Disabled,
      suspense = true,
      refetchOnMount = true,
      refetchOnFocus = true,
      refetchOnReconnect = true,
      refetchInterval,
    } = options;
    const optInput = (options as { input?: Record<string, unknown> }).input;
    const cacheKey = createKey(
      optInput !== undefined
        ? { path: options.path, input: optInput }
        : { path: options.path },
    );
    const didMount = React.useRef(false);
    const optionsRef = React.useRef(options);
    React.useLayoutEffect(() => {
      optionsRef.current = options;
    });
    const intervalTime = disabled
      ? undefined
      : typeof refetchInterval === "function"
      ? refetchInterval(
        (cache.get(cacheKey) as CachedResponse<Paths, Path> | undefined)
          ?.data,
      )
      : refetchInterval;

    const doRefetch = React.useEffectEvent(() => {
      load({ ...options, staleTime }).catch(() => {});
    });

    const doIntervalRefetch = React.useEffectEvent(() => {
      load({ ...options, staleTime: 0 }).catch(() => {});
    });

    const handleVisibilityChange = React.useEffectEvent(() => {
      if (document.visibilityState === "visible") {
        doRefetch();
      }
    });

    React.useEffect(() => {
      if (disabled) return;

      if (refetchOnMount && !didMount.current) {
        doRefetch();
      }
      didMount.current = true;

      let interval: ReturnType<typeof setInterval> | undefined;

      if (intervalTime) {
        interval = setInterval(doIntervalRefetch, intervalTime);
      }

      if (refetchOnFocus) {
        window.addEventListener("focus", doRefetch, false);
        window.addEventListener(
          "visibilitychange",
          handleVisibilityChange,
          false,
        );
      }

      if (refetchOnReconnect) {
        window.addEventListener("online", doRefetch, false);
      }

      return () => {
        if (interval) clearInterval(interval);
        window.removeEventListener("focus", doRefetch);
        window.removeEventListener("visibilitychange", handleVisibilityChange);
        window.removeEventListener("online", doRefetch);
      };
    }, [
      cacheKey,
      refetchOnMount,
      intervalTime,
      refetchOnFocus,
      refetchOnReconnect,
      staleTime,
      disabled,
    ]);

    let cached = React.useSyncExternalStore<
      CachedResponse<Paths, Path> | undefined
    >(
      React.useCallback(
        (onStoreChange) => {
          const unsubscribe = cache.didChange.observe((keysChanged) => {
            if (keysChanged.includes(cacheKey)) {
              onStoreChange();
            }
          });

          refCount.set(cacheKey, (refCount.get(cacheKey) ?? 0) + 1);

          return () => {
            unsubscribe();
            refCount.set(cacheKey, (refCount.get(cacheKey) ?? 0) - 1);
          };
        },
        [cacheKey],
      ),
      React.useCallback(() => {
        return cache.get(cacheKey) as
          | CachedResponse<Paths, Path>
          | undefined;
      }, [cacheKey]),
      React.useCallback(() => {
        return cache.get(cacheKey) as
          | CachedResponse<Paths, Path>
          | undefined;
      }, [cacheKey]),
    );

    if (!disabled && (!cached || cached.status === "fetching")) {
      cached = cache.get(cacheKey) as CachedResponse<Paths, Path> | undefined;
      // Kick off the fetch if not already in-flight. load() writes the cache
      // entry synchronously before its first await, so the promise we hand to
      // React.use() is always the stable per-key reference — never a transient
      // outer async-function promise that changes identity on re-render.
      if (!cached) {
        load({ ...options, staleTime }).catch(() => {});
        cached = cache.get(cacheKey) as CachedResponse<Paths, Path> | undefined;
      }

      if (suspense) {
        React.use(cached!.promise);
      }
    }

    return React.useMemo((): any => {
      function invalidate() {
        const cached = cache.get(cacheKey);
        if (cached) {
          cached.createdAt = 0;
        }
      }
      const {
        status = "disabled",
        data,
        error,
        response,
      } = cache.get(cacheKey) ?? {};
      const hasCachedData = data !== undefined;
      const loaderStatus = status === "refetching" || status === "error"
        ? hasCachedData
          ? "success"
          : "error"
        : status;

      if (suspense && loaderStatus === "error") {
        throw new ErrorResponse(error, response);
      }

      return {
        data,
        error: loaderStatus === "success" ? undefined : error,
        response: loaderStatus === "error" || loaderStatus === "success"
          ? response
          : undefined,
        lastError: status === "error" ? { data: error, response } : undefined,
        status: loaderStatus,
        fetchStatus: status === "disabled" ? "uncached" : status,
        invalidate,
        refetch() {
          invalidate();
          return load(optionsRef.current as LoadOptions<Paths, Path>);
        },
      };
    }, [cacheKey, cached]);
  }

  /**
   * Fetches a GET endpoint and returns a discriminated union for inline rendering.
   *
   * The same as `useLoader` except it never throws a Promise or `ErrorResponse`.
   * Instead, all states are exposed through `status` so you can render them
   * inline without a `<Suspense>` or `<ErrorBoundary>` wrapper.
   *
   * The return type is a discriminated union on `status`. TypeScript narrows the
   * `data` and `error` fields automatically based on which branch you're in.
   *
   * `lastError` persists the most-recent error across refetches so you can show
   * a toast while serving stale data. `error` is cleared on the next successful
   * fetch; `lastError` is not.
   *
   * All trigger options (`refetchOnMount`, `refetchOnFocus`, `refetchOnReconnect`,
   * `refetchInterval`) work identically to `useLoader`.
   *
   * @example
   * ```tsx
   * function UserProfile({ id }: { id: number }) {
   *   const result = api.useInlineLoader({
   *     path: "GET /users/{id}",
   *     input: { path: { id } },
   *   });
   *
   *   if (result.status === "fetching") return <Spinner />;
   *   if (result.status === "error") return <ErrorMessage error={result.error} />;
   *
   *   // status === "success": data is typed and defined
   *   return <p>{result.data.name}</p>;
   * }
   * ```
   *
   * @example
   * ```tsx
   * // Show stale data with a background-refresh indicator
   * const result = api.useInlineLoader({ path: "GET /feed" });
   *
   * return (
   *   <div>
   *     {result.lastError && <Toast message="Refresh failed" />}
   *     {result.status !== "fetching" && <FeedList items={result.data} />}
   *   </div>
   * );
   * ```
   */
  function useInlineLoader<
    Path extends LoadablePaths<Paths>,
    Disabled extends Readonly<boolean> = Readonly<false>,
  >(
    options: UseInlineLoaderOptions<Paths, Path, Disabled>,
  ): UseInlineLoaderResult<Paths, Path, Disabled> {
    // @ts-expect-error: it's fine
    return useLoader({ ...options, suspense: false });
  }

  /**
   * Manages a single mutation: tracks status and exposes a `send` function.
   *
   * `useAction` is for write operations — POST, PUT, PATCH, DELETE. It does not
   * read from or write to the cache. After a successful `send`, call `invalidate`
   * or `refetch` on any GET paths that should reflect the change.
   *
   * Each `send` call is independent. If `send` is called a second time before the
   * first resolves, the first call's status update is discarded — only the last
   * in-flight call drives the `status` state.
   *
   * `send` throws an `ErrorResponse` on failure. Catch it, or use the `onError`
   * option to handle errors declaratively without wrapping every call site.
   *
   * @example
   * ```tsx
   * function CreateUserForm() {
   *   const { status, send } = api.useAction({
   *     path: "POST /users",
   *     onSuccess: (user) => {
   *       api.invalidate({ path: "GET /users" });
   *       toast.success(`Created ${user.name}`);
   *     },
   *     onError: (err) => toast.error(err.message),
   *   });
   *
   *   async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
   *     e.preventDefault();
   *     const form = new FormData(e.currentTarget);
   *     await send({ body: { name: form.get("name") as string } });
   *   }
   *
   *   return (
   *     <form onSubmit={handleSubmit}>
   *       <input name="name" />
   *       <button disabled={status === "fetching"}>
   *         {status === "fetching" ? "Saving…" : "Create"}
   *       </button>
   *     </form>
   *   );
   * }
   * ```
   *
   * @example
   * ```tsx
   * // DELETE with a path param
   * const { send } = api.useAction({ path: "DELETE /users/{id}" });
   *
   * await send({ path: { id: userId } });
   * api.purge({ path: "GET /users/{id}", input: { path: { id: userId } } });
   * api.invalidate({ path: "GET /users" });
   * ```
   */
  function useAction<
    Method extends Uppercase<HttpMethod>,
    Path extends Extract<PathsWithMethod<Paths, Lowercase<Method>>, string>,
  >(
    options: UseActionOptions<Paths, Path, Method>,
  ): UseActionResult<Paths, Path, Method> {
    const [status, setStatus] = React.useState<
      "idle" | "fetching" | "success" | "error"
    >("idle");

    const latestOptions = React.useRef(options);
    const currentRef = React.useRef<Promise<unknown>>(undefined);

    React.useEffect(() => {
      if (options.path !== latestOptions.current.path) {
        setStatus("idle");
      }
      latestOptions.current = options;
    });

    const send = React.useCallback(
      async (
        input: Input<Paths, Path, Lowercase<Method>> extends { input: infer I }
          ? I
          : void,
        requestInit?: Omit<RequestInit, "method" | "body">,
      ): Promise<Data<Paths, Path, Lowercase<Method>>> => {
        setStatus("fetching");
        const { onError, onSuccess, onSettled } = latestOptions.current;
        const fullInput = (input !== undefined ? { input } : {}) as Input<
          Paths,
          Path,
          Lowercase<Method>
        >;
        const promise = (currentRef.current = fetch_(
          latestOptions.current.path as typeof options.path,
          {
            ...requestInit,
            ...fullInput,
          },
        ));

        try {
          const res = await promise;

          if (res.error) {
            throw new ErrorResponse<ErrorData<Paths, Path, Lowercase<Method>>>(
              res.error as ErrorData<Paths, Path, Lowercase<Method>>,
              res.response,
            );
          }

          if (currentRef.current === promise) {
            setStatus("success");
          }

          const data = res.data as Data<Paths, Path, Lowercase<Method>>;
          Promise.all([
            onEachSuccess?.(data),
            onSuccess?.(data, res.response),
            onSettled?.(data, undefined, res.response),
          ]).catch(() => {});

          return data;
        } catch (err) {
          if (currentRef.current === promise) {
            setStatus("error");
          }

          if (err instanceof ErrorResponse) {
            const typedErr = err as ErrorResponse<
              ErrorData<Paths, Path, Lowercase<Method>>
            >;
            Promise.all([
              onEachError?.(typedErr),
              onError?.(typedErr.data, typedErr.response!),
              onSettled?.(undefined, typedErr, typedErr.response),
            ]).catch(() => {});
            throw typedErr;
          }

          throw err;
        }
      },
      // eslint-disable-next-line react-hooks/exhaustive-deps
      [],
    );

    return React.useMemo(() => ({ status, send }), [status, send]);
  }

  /**
   * Marks one or more cache entries as stale without refetching them.
   *
   * The next event that would trigger a fetch — mount, focus, reconnect, interval,
   * or manual `refetch` — will issue a fresh request. Until then, stale data
   * remains in the cache and any mounted components continue to show it.
   *
   * For an immediate refetch, use `refetch` instead.
   *
   * Accepts either an exact path+input key, or a `match` function for
   * bulk-invalidating multiple entries (e.g., all entries for a given path
   * regardless of query parameters).
   *
   * @example
   * ```ts
   * // Exact key
   * api.invalidate({ path: "GET /users/{id}", input: { path: { id: 42 } } });
   *
   * // All entries for /users (any query params), but only those with active subscribers
   * api.invalidate({
   *   match: (key, refCount) =>
   *     key.path === "GET /users" && refCount > 0,
   * });
   * ```
   */
  function invalidate<Path extends LoadablePaths<Paths>>(
    options: PathMatcher<Paths, Path>,
  ): void {
    if ("match" in options) {
      for (const key of cache.keys()) {
        if (options.match(JSON.parse(key), refCount.get(key) ?? 0)) {
          const cached = cache.get(key);
          if (cached) {
            cached.createdAt = 0;
          }
        }
      }
    } else {
      const cacheKey = createKey(options);
      const cached = cache.get(cacheKey);
      if (cached) {
        cached.createdAt = 0;
      }
    }
  }

  /**
   * Invalidates and immediately refetches one or more cache entries.
   *
   * Equivalent to calling `invalidate` followed by `load` for each matching key.
   * Awaiting `refetch` waits for all matched requests to settle.
   *
   * Call this after a mutation to synchronously refresh data before the next render.
   * If you don't need to wait for the refresh, `invalidate` is cheaper.
   *
   * @example
   * ```ts
   * // After creating a user, immediately refresh the list
   * await api.fetch("POST /users", { input: { body: newUser } });
   * await api.refetch({ path: "GET /users" });
   * ```
   *
   * @example
   * ```ts
   * // Refetch all cached entries for any /projects path
   * await api.refetch({
   *   match: (key) => key.path.startsWith("GET /projects"),
   * });
   * ```
   */
  async function refetch<Path extends LoadablePaths<Paths>>(
    options: PathMatcher<Paths, Path>,
  ): Promise<void> {
    invalidate(options);

    if ("match" in options) {
      const promises: unknown[] = [];

      for (const key of cache.keys()) {
        if (options.match(JSON.parse(key), refCount.get(key) ?? 0)) {
          promises.push(load(JSON.parse(key)));
        }
      }

      await Promise.all(promises);
    } else {
      await load(options);
    }
  }

  /**
   * Removes one or more entries from the cache entirely.
   *
   * Unlike `invalidate` — which marks entries stale but keeps data visible during
   * the next fetch — `purge` deletes the entry. Any component that was showing
   * stale data will immediately lose it. The next `load` or mount will start from
   * scratch with `status: "fetching"` and no prior data.
   *
   * Use `purge` when stale data must not be shown at all: after a logout, after
   * deleting a resource, or when you need a clean-slate re-fetch.
   *
   * @example
   * ```ts
   * // Remove a specific user from the cache after deletion
   * await api.fetch("DELETE /users/{id}", { input: { path: { id: 42 } } });
   * api.purge({ path: "GET /users/{id}", input: { path: { id: 42 } } });
   * api.invalidate({ path: "GET /users" }); // list can show stale data briefly
   * ```
   *
   * @example
   * ```ts
   * // Clear everything on logout
   * api.purge({ match: () => true });
   * ```
   */
  function purge<Path extends LoadablePaths<Paths>>(
    options: PathMatcher<Paths, Path>,
  ): void {
    if ("match" in options) {
      for (const key of cache.keys()) {
        if (options.match(JSON.parse(key), refCount.get(key) ?? 0)) {
          cache.delete(key);
        }
      }
    } else {
      const cacheKey = createKey(options);
      cache.delete(cacheKey);
    }
  }

  return {
    url,
    fetch: fetch_,
    load,
    hydrate,
    useLoader,
    useInlineLoader,
    useAction,
    invalidate,
    refetch,
    purge,
    /**
     * Stops the background cache-eviction timer.
     *
     * Call this in test teardown or when the client is no longer needed to
     * prevent the timer from keeping the process alive.
     */
    destroy() {
      clearInterval(evictionInterval);
    },
  };
}

function subject<T>(initialState: T): Subject<T> {
  const observers: Set<Observer<T>> = new Set();
  let state = initialState;

  return {
    setState(nextState: T) {
      state = nextState;
      for (const listener of observers) {
        listener(nextState);
      }
    },
    getState() {
      return state;
    },
    observe(observer: Observer<T>) {
      observers.add(observer);
      return () => {
        observers.delete(observer);
      };
    },
    unobserve(observer: Observer<T>) {
      observers.delete(observer);
    },
  };
}

class SubjectMap<K, V> extends Map<K, V> {
  didChange: Subject<K[]>;
  private pendingKeys: K[] | null = null;

  constructor(initialValue?: [K, V][]) {
    super(initialValue);
    this.didChange = subject([]);
  }

  private scheduleNotify(key: K) {
    if (this.pendingKeys === null) {
      this.pendingKeys = [key];
      queueMicrotask(() => {
        const keys = this.pendingKeys!;
        this.pendingKeys = null;
        this.didChange.setState(keys);
      });
    } else {
      this.pendingKeys.push(key);
    }
  }

  override set(key: K, value: V) {
    super.set(key, value);
    this.scheduleNotify(key);
    return this;
  }

  override delete(key: K) {
    const deleted = super.delete(key);
    this.scheduleNotify(key);
    return deleted;
  }

  override clear() {
    const keys = [...this.keys()];
    super.clear();
    for (const key of keys) {
      this.scheduleNotify(key);
    }
  }
}

function defaultShouldRetryOnError<T extends ErrorResponse<any>>(err: T) {
  // 4xx are client errors — not transient, never worth retrying
  if (err.response && err.response.status < 500) return false;
  return true;
}

async function retry<T, E extends ErrorResponse<any>>(
  fn: () => Promise<{ data: T; response: Response }>,
  retries: number,
  shouldRetry: (
    error: E,
    retryCount: number,
  ) => void | boolean | Promise<void | boolean>,
): Promise<{ data: T; response: Response }> {
  let retryCount = 0;

  while (true) {
    try {
      return await fn();
    } catch (error) {
      if (!(error instanceof ErrorResponse)) {
        throw error;
      }

      if (retryCount >= retries) {
        throw error;
      }

      retryCount++;
      if ((await shouldRetry(error as E, retryCount)) === false) {
        throw error;
      }
    }
  }
}

/**
 * Options for {@link createClient}.
 *
 * All options are optional. Sensible defaults are chosen for typical SPA usage.
 */
export type ClientOptions<Paths extends {}> = {
  /** Base URL prepended to every request path. Default: `""`. */
  baseUrl?: string;
  /**
   * How long (ms) an unmounted cache entry survives before being evicted.
   * Eviction only runs when `refCount === 0` (no mounted subscribers).
   * Default: `300_000` (5 minutes).
   */
  cacheTime?: number;
  /**
   * Window (ms) during which a successful cache entry is served without
   * re-fetching, even on mount or focus. Default: `1000` (1 second).
   *
   * Set to `0` to always re-fetch on mount. Set to `Infinity` to never
   * re-fetch in the background.
   */
  staleTime?: number;
  /**
   * Maximum number of retry attempts on retriable errors (5xx by default).
   * Retries use exponential backoff with jitter. Default: `3`.
   */
  retries?: number;
  /**
   * Predicate called before each retry. Return `false` to abort immediately;
   * return `true` or `void` to proceed. May be async.
   *
   * Default: retry on any 5xx; never retry 4xx.
   *
   * @example
   * ```ts
   * // Only retry network errors, not HTTP errors
   * shouldRetry: (err) => err.response === undefined
   * ```
   */
  shouldRetry?: (
    error: ErrorResponse<
      Exclude<ResponseUnion<Paths, HttpMethod>["error"], undefined>
    >,
    retryCount: number,
  ) => void | boolean | Promise<void | boolean>;
  /**
   * When `true`, logs each response (HTTP status, URL, headers, body) to the
   * console. Default: `false`.
   */
  debug?: boolean;
  /**
   * Factory called before every request to produce per-request `RequestInit`
   * fields. Evaluated lazily so auth tokens are always fresh.
   *
   * @example
   * ```ts
   * requestInit: () => ({
   *   headers: { Authorization: `Bearer ${getAccessToken()}` },
   *   credentials: "include",
   * })
   * ```
   */
  requestInit?: () => Pick<RequestInit, "cache" | "credentials" | "mode"> & {
    headers?: HeadersInit | Record<string, string>;
  };
  /**
   * Replaces the default query-string serialization. Receives the raw query
   * params object and must return a URL-encoded string (without `?`).
   */
  querySerializer?: <T = unknown>(queryParams: T) => string;
  /**
   * Called after every successful `useAction` send across all paths. Useful for
   * analytics, global loading indicators, or cross-cutting side effects.
   */
  onEachSuccess?: (
    data: Exclude<
      ResponseUnion<Paths, HttpMethod>["data"],
      undefined | Record<string, never>
    >,
  ) => void;
  /**
   * Called after every failed `useAction` send across all paths. Useful for
   * global error reporting (Sentry, Datadog, etc.).
   */
  onEachError?: (
    error: ErrorResponse<
      Exclude<ResponseUnion<Paths, HttpMethod>["error"], undefined>
    >,
  ) => void;
  /**
   * Adds extra fields to every cache key. Use this to namespace the cache
   * per tenant, locale, or any other dimension that affects response content.
   *
   * @example
   * ```ts
   * // Separate cache per org so tenant A never serves tenant B's data
   * extendCacheKey: (opt) => ({ ...opt, orgId: getCurrentOrgId() })
   * ```
   */
  extendCacheKey?: (options: {
    path: `GET ${LoadablePaths<Paths>}`;
    input?: Record<string, unknown>;
  }) => { path: string; input?: Record<string, unknown> } & {
    [key: string]: unknown;
  };
};

type ResponseUnion<Paths extends {}, Method extends HttpMethod> = {
  [Path in keyof Paths]: {
    [M in Method]: Paths[Path] extends Record<M, { responses: any }>
      ? FetchResponse<Paths[Path][M], { parseAs: "json" }, "application/json">
      : never;
  }[Method];
}[keyof Paths];

/**
 * A single entry in the shared cache.
 *
 * Returned by `load`. The `promise` field is useful when you need to await
 * an in-flight request that another caller already started.
 */
export type CachedResponse<
  Paths extends {},
  Path extends Extract<keyof Paths, string>,
> = {
  data: Data<Paths, Path, "get"> | undefined;
  error: ErrorData<Paths, Path, "get"> | undefined;
  response: Response | undefined;
  status: FetchStatus;
  promise: Promise<unknown>;
  createdAt: number;
};

type FetchStatus = "fetching" | "refetching" | "success" | "error";

type ErrorEnvelope = { error?: { message?: string } };

/**
 * Wraps an API error response with a typed `.data` payload.
 *
 * Thrown by `useLoader` (when `suspense: true`), `useAction.send`, and `load`
 * (for non-HTTP errors). Caught by `<ErrorBoundary>` when thrown from a hook.
 *
 * `.message` is extracted from `data.error.message` if present; otherwise
 * falls back to `"API error"`.
 *
 * @example
 * ```ts
 * try {
 *   await api.send({ body: newUser });
 * } catch (err) {
 *   if (err instanceof ErrorResponse) {
 *     console.error(err.data);       // typed error body
 *     console.error(err.response);   // raw Response
 *   }
 * }
 * ```
 *
 * @example
 * ```tsx
 * // ErrorBoundary catches ErrorResponse thrown by useLoader in suspense mode
 * function ErrorFallback({ error }: { error: unknown }) {
 *   if (error instanceof ErrorResponse) {
 *     return <p>API error {error.response?.status}: {error.message}</p>;
 *   }
 *   return <p>Unexpected error</p>;
 * }
 * ```
 */
export class ErrorResponse<T extends ErrorData<any, any, any>> extends Error {
  data: T;
  response: Response | undefined;
  constructor(data: T, response?: Response) {
    super((data as ErrorEnvelope)?.error?.message ?? "API error");
    this.name = "ErrorResponse";
    this.data = data;
    this.response = response;
  }
}

function encodeKey({
  path,
  input,
  ...other
}: {
  path: string;
  input?: Record<string, unknown>;
}) {
  const processed = input ? removeEmptyKeys(input) : undefined;
  return JSON.stringify({
    path,
    input: processed && Object.keys(processed).length
      ? sortObject(processed)
      : undefined,
    ...other,
  });
}

function removeEmptyKeys(obj: Record<string, unknown>) {
  const next: Record<string, unknown> = {};

  for (const key in obj) {
    if (
      obj[key] === undefined
      || (typeof obj[key] === "object"
        && obj[key] !== null
        && !Object.keys(obj[key] as object).length)
    ) {
      continue;
    }

    next[key] = obj[key];
  }

  return next;
}

function sortObject(obj: Record<string, unknown>): unknown {
  if (typeof obj !== "object" || obj === null) {
    return obj;
  }

  if (Array.isArray(obj)) {
    const s = Array.from<unknown>({ length: obj.length });
    for (let i = 0; i < obj.length; i++) {
      s[i] = sortObject(obj[i] as Record<string, unknown>);
    }
    return s;
  }

  const sorted: Record<string, unknown> = {};
  const keys = Object.keys(obj).sort();
  for (let i = 0; i < keys.length; i++) {
    const key = keys[i]!;
    sorted[key] = sortObject(obj[key] as Record<string, unknown>);
  }

  return sorted;
}

const REDACTED_HEADERS = new Set(["authorization", "cookie", "set-cookie"]);

function logResponse(res: { data?: unknown; response: Response }) {
  const { response } = res;
  const headers = Object.fromEntries(
    [...response.headers.entries()].filter(
      ([k]) => !REDACTED_HEADERS.has(k.toLowerCase()),
    ),
  );
  console.log(`📮 %c${response.status} ${response.url}`, "color: #999");
  console.log("Headers\n", headers);
  console.log("Body\n", res.data);
}

/** Options for the imperative {@link createClient} `load` method. */
export type LoadOptions<
  Paths extends {},
  Path extends Extract<keyof Paths, string>,
> = {
  /** Path prefixed with `"GET "`, e.g. `"GET /users"` or `"GET /users/{id}"`. */
  path: `GET ${Path}`;
  /**
   * Override the client-level `staleTime` for this call.
   * Pass `0` to force a fresh request even if a cached entry exists.
   */
  staleTime?: number;
  /** Override the client-level `retries` for this call. */
  retries?: number;
  /** Override the client-level `shouldRetry` predicate for this call. */
  shouldRetry?: (
    error: ErrorResponse<ErrorData<Paths, Path, "get">>,
    retryCount: number,
  ) => void | boolean | Promise<void | boolean>;
  /** Passed to `fetch` to support cancellation. */
  signal?: AbortSignal;
} & Input<Paths, Path, "get">;

/** Options for {@link createClient} `useLoader` and `useInlineLoader`. */
export type UseLoaderOptions<
  Paths extends {},
  Path extends Extract<keyof Paths, string>,
  Disabled extends Readonly<boolean>,
> = {
  /** Path prefixed with `"GET "`, e.g. `"GET /users"` or `"GET /users/{id}"`. */
  path: `GET ${Path}`;
  /**
   * Override the client-level `staleTime` for this hook.
   * Pass `0` to always re-fetch on mount.
   */
  staleTime?: number;
  /**
   * When `true`, the hook issues no requests and returns `status: "disabled"`.
   * TypeScript narrows the return type when the literal `true` is passed —
   * useful to skip fetching until a required value (e.g., a user ID) is available.
   */
  disabled?: Disabled;
  /**
   * When `true` (the default), the hook throws a Promise while loading so a
   * parent `<Suspense>` boundary can render a fallback. Set to `false` to opt
   * out — equivalent to using `useInlineLoader`.
   */
  suspense?: boolean;
  /** Re-fetch when the component mounts. Default: `true`. */
  refetchOnMount?: boolean;
  /** Re-fetch when the window regains focus or the tab becomes visible. Default: `true`. */
  refetchOnFocus?: boolean;
  /** Re-fetch when the browser comes back online. Default: `true`. */
  refetchOnReconnect?: boolean;
  /**
   * Interval (ms) for background polling, or a function that returns the interval
   * based on the current data. Return `false` to pause polling.
   *
   * @example
   * ```ts
   * // Poll every 5s unconditionally
   * refetchInterval: 5_000
   *
   * // Poll every 2s while a job is running; stop when done
   * refetchInterval: (data) => data?.status === "running" ? 2_000 : false
   * ```
   */
  refetchInterval?:
    | number
    | ((
      data: Data<Paths, Path, "get"> | undefined,
    ) => number | false);
} & Input<Paths, Path, "get">;

/**
 * Return type of `useLoader`.
 *
 * When `Disabled` is `false` (the default), `data` and `response` are always
 * defined — Suspense guarantees the component only renders after a successful
 * fetch. When `Disabled` is `true`, all fields are `undefined` and `status`
 * is `"disabled"`.
 */
export type UseLoaderResult<
  Paths extends {},
  Path extends Extract<keyof Paths, string>,
  Disabled extends Readonly<boolean>,
> =
  & (Disabled extends false ? {
      data: Data<Paths, Path, "get">;
      error: undefined;
      response: Response;
      lastError: undefined;
      status: "success";
      fetchStatus: FetchStatus;
    }
    : {
      data: undefined;
      error: undefined;
      response: undefined;
      lastError: undefined;
      status: "disabled";
      fetchStatus: "uncached" | FetchStatus;
    })
  & {
    invalidate(): void;
    refetch(): Promise<CachedResponse<Paths, Path>>;
  };

/** Options for {@link createClient} `useInlineLoader`. Identical to `UseLoaderOptions` minus `suspense`. */
export type UseInlineLoaderOptions<
  Paths extends {},
  Path extends Extract<keyof Paths, string>,
  Disabled extends Readonly<boolean>,
> = Omit<UseLoaderOptions<Paths, Path, Disabled>, "suspense">;

/**
 * Discriminated union returned by `useInlineLoader`.
 *
 * Narrow on `status` to access typed `data` and `error` fields:
 * - `"fetching"` — initial load in progress; `data` and `error` are `undefined`.
 * - `"success"` — data is available; `error` is `undefined`.
 * - `"error"` — fetch failed; `error` is typed; `data` may be `undefined` (no prior success).
 * - `"disabled"` — hook is disabled; all payload fields are `undefined`.
 *
 * `lastError` holds the most-recent error across refetches. It persists while
 * data is visible (e.g., refetch failed but stale data is still shown). `error`
 * is cleared on the next successful fetch; `lastError` is not.
 */
export type UseInlineLoaderResult<
  Paths extends {},
  Path extends Extract<keyof Paths, string>,
  Disabled extends Readonly<boolean>,
> =
  & (Disabled extends false ?
      | {
        data: Data<Paths, Path, "get">;
        error: undefined;
        response: Response;
        lastError:
          | {
            data: ErrorData<Paths, Path, "get"> | undefined;
            response: Response | undefined;
          }
          | undefined;
        status: "success";
        fetchStatus: FetchStatus;
      }
      | {
        data: undefined;
        error: undefined;
        response: undefined;
        lastError: undefined;
        status: "fetching";
        fetchStatus: Extract<FetchStatus, "fetching">;
      }
      | {
        data: undefined;
        error: ErrorData<Paths, Path, "get">;
        response: Response;
        lastError: {
          data: ErrorData<Paths, Path, "get"> | undefined;
          response: Response | undefined;
        };
        status: "error";
        fetchStatus: FetchStatus;
      }
    : {
      data: undefined;
      error: undefined;
      response: undefined;
      lastError: undefined;
      status: "disabled";
      fetchStatus: "uncached" | FetchStatus;
    })
  & {
    invalidate(): void;
    refetch(): Promise<CachedResponse<Paths, Path>>;
  };

/** Options for {@link createClient} `useAction`. */
export type UseActionOptions<
  Paths extends {},
  Path extends Extract<keyof Paths, string>,
  Method extends Uppercase<HttpMethod>,
> = {
  /**
   * HTTP method and path encoded as a string literal, e.g. `"POST /users"` or
   * `"DELETE /users/{id}"`.
   */
  path: `${Method} ${Path}`;
  /**
   * Called when `send` fails. Receives the typed error body and the raw Response.
   * Errors thrown here are silently swallowed — use for side effects only.
   */
  onError?: (
    err: ErrorData<Paths, Path, Lowercase<Method>>,
    response: Response,
  ) => Promise<void> | void;
  /**
   * Called when `send` succeeds. Receives the response data and the raw Response.
   * Errors thrown here are silently swallowed — use for side effects only.
   */
  onSuccess?: (
    output: Data<Paths, Path, Lowercase<Method>>,
    response: Response,
  ) => Promise<void> | void;
  /**
   * Called when `send` settles — whether it succeeded or failed. Receives the
   * data (on success) or `undefined` (on error), the `ErrorResponse` (on
   * error) or `undefined` (on success), and the raw `Response`. Useful for
   * cleanup that must run regardless of outcome (closing a modal, resetting a
   * form, stopping a spinner). Errors thrown here are silently swallowed —
   * use for side effects only.
   */
  onSettled?: (
    data: Data<Paths, Path, Lowercase<Method>> | undefined,
    error: ErrorResponse<ErrorData<Paths, Path, Lowercase<Method>>> | undefined,
    response: Response | undefined,
  ) => Promise<void> | void;
};

/**
 * Return type of `useAction`.
 *
 * `status` reflects the most-recent `send` call:
 * - `"idle"` — `send` has never been called (or the path changed).
 * - `"fetching"` — a request is in-flight.
 * - `"success"` — the last `send` completed successfully.
 * - `"error"` — the last `send` failed.
 *
 * `send` returns a Promise that resolves to the response data, or rejects
 * with an `ErrorResponse` on failure.
 */
export type UseActionResult<
  Paths extends {},
  Path extends Extract<keyof Paths, string>,
  Method extends Uppercase<HttpMethod>,
> = {
  status: "idle" | "fetching" | "success" | "error";
  send(
    input: Input<Paths, Path, Lowercase<Method>> extends { input: infer I } ? I
      : void,
    requestInit?: Omit<RequestInit, "method" | "body">,
  ): Promise<Data<Paths, Path, Lowercase<Method>>>;
};

/** A `Response` with a typed `.json()` method. */
export type TypedResponse<T> = Omit<Response, "json"> & {
  json(): Promise<T>;
};

/**
 * The `input` type for a given path + method.
 *
 * Resolves to `{ input: { query?, path?, body? } }` when the operation has
 * parameters or a request body, or `{}` when it has neither. Used to type
 * the `input` field on `load`, `useLoader`, and `fetch`.
 */
// Pick only keys that exist in T, avoiding `unknown` for absent keys
type SafePick<T, K extends string> = Pick<T, Extract<keyof T, K>>;

/**
 * Wraps `Shape` in `{ input: Shape }`, marking `input` as optional iff every
 * field inside `Shape` is itself optional. This lets callers omit `input`
 * entirely for ops where nothing inside it is required (e.g., a `GET` with
 * only optional query params), while still requiring `input` when at least
 * one field inside is required (e.g., a path param).
 */
type WrapInput<Shape> = {} extends Shape ? { input?: Shape } : { input: Shape };

export type Input<
  Paths extends {},
  Path extends Extract<keyof Paths, string>,
  Method extends HttpMethod,
> = Paths[Path] extends Record<Method, { parameters: any }>
  ? Paths[Path][Method]["parameters"] extends {
    query?: never;
    header?: never;
    path?: never;
    cookie?: never;
  } ? Paths[Path][Method] extends { requestBody?: never } ? {}
    : WrapInput<
      Simplify<{ body: RequestBodyOption<Paths[Path][Method]>["body"] }>
    >
  : Paths[Path][Method] extends { requestBody?: never } ? WrapInput<
      ConditionalExcept<
        SafePick<Paths[Path][Method]["parameters"], "query" | "path">,
        undefined
      >
    >
  : WrapInput<
    Simplify<
      ConditionalExcept<
        SafePick<Paths[Path][Method]["parameters"], "query" | "path">,
        undefined
      > & { body: RequestBodyOption<Paths[Path][Method]>["body"] }
    >
  >
  : {};

/** The raw `openapi-fetch` response type for a path + method. */
export type Output<
  Paths extends {},
  Path extends Extract<keyof Paths, string>,
  Method extends HttpMethod,
> = Paths[Path] extends Record<Method, { responses: any }> ? FetchResponse<
    Paths[Path][Method],
    { parseAs: "json" },
    "application/json"
  >
  : never;

/** The success data type for a path + method (excludes `undefined`). */
export type Data<
  Paths extends {},
  Path extends Extract<keyof Paths, string>,
  Method extends HttpMethod,
> = Exclude<Output<Paths, Path, Method>["data"], undefined>;

/** The error body type for a path + method (excludes `undefined`). */
export type ErrorData<
  Paths extends {},
  Path extends Extract<keyof Paths, string>,
  Method extends HttpMethod,
> = Exclude<Output<Paths, Path, Method>["error"], undefined>;

/**
 * Identifies one or more cache entries for `invalidate`, `refetch`, and `purge`.
 *
 * Two forms:
 * - **Exact key** — a path + optional `input` matching a specific cache entry.
 * - **Predicate** — a `match` function called for every entry in the cache.
 *   Receives the parsed cache key and its current subscriber count (`refCount`).
 *
 * @example
 * ```ts
 * // Exact key
 * { path: "GET /users/{id}", input: { path: { id: 42 } } }
 *
 * // All /users entries with active subscribers
 * { match: (key, refCount) => key.path === "GET /users" && refCount > 0 }
 *
 * // Nuke everything (e.g., on logout)
 * { match: () => true }
 * ```
 */
export type PathMatcher<
  Paths extends {},
  Path extends Extract<keyof Paths, string>,
> =
  | ({ path: `GET ${Path}` } & Input<Paths, Path, "get">)
  | {
    match(
      key: { path: `GET ${Path}` } & Input<Paths, Path, "get">,
      refCount: number,
    ): boolean;
  };

export type LoadResult<T extends CachedResponse<any, any>> =
  | {
    status: "error";
    data: undefined | T["data"];
    error: T["error"] extends { code: string; message: string } | undefined
      ? T["error"]
      : never;
    promise: Promise<LoadResult<T>>;
  }
  | {
    status: "success" | "refetching";
    data: T["data"];
    error: undefined;
    promise: Promise<LoadResult<T>>;
  }
  | {
    status: "fetching";
    data: undefined;
    error: undefined;
    promise: Promise<LoadResult<T>>;
  };

/** The subset of `Paths` keys that have a `get` method — the only paths valid for `useLoader` and `load`. */
export type LoadablePaths<Paths extends {}> = Extract<
  PathsWithMethod<Paths, "get">,
  string
>;

type Observer<T> = {
  (state: T): void;
};

type Subject<T> = {
  setState(state: T): void;
  getState(): T;
  observe(observer: Observer<T>): () => void;
  unobserve(observer: Observer<T>): void;
};
